version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - mguidon
      - sanderegg
    assignees:
      - sanderegg

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
    reviewers:
      - sanderegg
    assignees:
      - sanderegg
