codecov:
  require_ci_to_pass: yes
  branch: main

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default:
        informational: true
        threshold: 1%
        paths:
          - services

    patch:
      default:
        informational: true
        threshold: 1%
        paths:
          - services

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
