version: '3.6' # Don't touch
services:
  dask-gateway-server-osparc:
    image: local/osparc-dask-gateway:${BUILD_TARGET:?build_target_required}
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/gateway:/mnt/gateway
    networks:
       - dask_net
    environment:
      - GATEWAY_WORK_FOLDER=/mnt/gateway

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  dask_net:
    attachable: true
    internal: false
    ipam:
      driver: default
      config:
        - subnet: "172.9.0.0/16"

volumes:
  gateway_data: {}
  portainer_data: {}