version: '3.6' # Don't touch
services:
  dask-gateway-server-osparc:
    image: local/osparc-dask-gateway:${BUILD_TARGET:?build_target_required}
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gateway_data:/mnt/gateway
    networks:
       - dask_net
    environment:
      - GATEWAY_WORK_FOLDER=/mnt/gateway
      - SIDECAR_IMAGE=mguidon/dask-sidecar:production

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  volume-sync:
    image: mguidon/osparc-volume-sync:production
    restart: always
    volumes:
      - gateway_data:/volumes/sync
    networks:
      - volume-sync
    environment:
      HOSTNAME: volume-sync
      SYNC_TYPE: ALL
      WAIT_BEFORE_SYNC: 1
      SYNC_INTERVAL: 5
      DEBUG: 1
    deploy:
      mode: global
      endpoint_mode: dnsrr
      
networks:
  dask_net:
    attachable: true
    internal: false
    ipam:
      driver: default
      config:
        - subnet: "172.9.0.0/16"
  volume-sync:
    driver: overlay

volumes:
  gateway_data:
  portainer_data: