version: "3.8"
services:
  osparc-dask-gateway:
    image: local/${SERVICE_NAME}:${BUILD_TARGET:?build_target_required}
    build:
      context: ./
      dockerfile: Dockerfile
      cache_from:
        - local/${SERVICE_NAME}:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/osparc-dask-gateway:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/osparc-dask-gateway:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/osparc-dask-gateway:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
