version: '3.6' # Don't touch
services:
  osparc-gateway-server:
    environment:
      - SC_BOOT_MODE=${SC_BOOT_MODE:-default}
    ports:
      - mode: ingress
        target: 3000
        published: 3100 # ptvsd port
        protocol: tcp
