version: "3.6"
services:
  osparc-gateway-server:
    image: local/osparc-gateway-server:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/osparc-gateway-server/Dockerfile
      cache_from:
        - local/osparc-gateway-server:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/osparc-gateway-server:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/osparc-gateway-server:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/osparc-gateway-server:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"

  volume-sync:
    image: local/volume-sync:production
    build:
      context: ../
      dockerfile: services/volume-sync/Dockerfile
      cache_from:
        - local/volume-sync:production
        - ${DOCKER_REGISTRY:-itisfoundation}/volume-sync:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/volume-sync:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/volume-sync:release-github-latest
      target: production
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
