version: '3.6' # Don't touch
services:
  dask-gateway-server-osparc:
    environment:
      - SC_BOOT_MODE=debug-ptvsd
      - LOG_LEVEL=debug
      - DEBUG=true
    volumes:
      - ./gateway:/devel/services/osparc-dask-gateway
