version: '3.6' # Don't touch
services:
  osparc-gateway-server:
    environment:
      - SC_BOOT_MODE=debug-ptvsd
      - LOG_LEVEL=debug
      - DEBUG=true
    volumes:
      - ./gateway:/devel/services/osparc-gateway-server
