version: "3.8"
services:
  osparc-dask-gateway:
    image: local/osparc-volume-sync:${BUILD_TARGET:?build_target_required}
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"